version: '3.7'
services:
  postgres:
    image: postgres:15
    environment:
      PGPORT: 5999
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - "5999:5999"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d/
    container_name: postgres

  vtp-inntektsmelding:
    image: europe-north1-docker.pkg.dev/nais-management-233d/teamforeldrepenger/navikt/vtp:latest
    environment:
      TZ: Europe/Oslo
      NO_NAV_MODIG_SECURITY_APPCERT_KEYSTORE: /app/.modig/keystore.jks
      JAVAX_NET_SSL_TRUSTSTORE: /app/.modig/truststore.jks
      CREATE_TOPICS: teamforeldrepenger.familie-vedtakfattet-v1
      KAFKA_FATTEVEDTAK_TOPIC: teamforeldrepenger.familie-vedtakfattet-v1
    volumes:
      - "~/.modig:/app/.modig"
    ports:
      - "8060:8060"
      - "8063:8063"
      - "8636:8636"
      - "9093:9093"
      - "9092:9092"
      - "8389:8389"
    container_name: vtp
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8060/rest/isReady" ]
      interval: 30s
      timeout: 5s

  arbeidsgiver-notifikasjon-fake-producer-api:
    image: ghcr.io/navikt/arbeidsgiver-notifikasjon-produsent-api/fake-produsent-api:latest
    ports:
      - "8072:8080"
    environment:
      ALWAYS_SUCCESSFUL_RESPONSE: true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8072/rest/isReady" ]
      interval: 30s
      timeout: 5s
