name: Bygg og deploy

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - '.editorconfig'
      - '.java-version'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'lokalutvikling/**'
      - '.github/*.yml'

jobs:
  build-app:
    name: Build
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: navikt/sif-gha-workflows/.github/workflows/maven-build-app-db.yml@main
    with:
      java-version: 21
      build-image: ${{ github.actor != 'dependabot[bot]' }}
      push-image: ${{ github.ref_name == github.event.repository.default_branch}}
      upload-image: ${{ github.ref_name != github.event.repository.default_branch }} # TODO: hør med Qadeer om denne trengs
      db_schema: k9inntektsmelding_unit
    secrets: inherit

  verdikjede-tester:
    name: Verdikjedetester
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      packages: read
    uses: navikt/sif-gha-workflows/.github/workflows/verdikjede-test-v2.yml@main
    if: ${{github.actor != 'dependabot[bot]'}}
    needs: build-app
    with:
      tag: ${{ needs.build-app.outputs.build-version }}
      suites: "pleiepenger,livetssluttfase"
      override_image_artifact_name: ${{ github.ref_name != github.event.repository.default_branch && needs.build-app.outputs.image-artifact-name || null }}
      image_version: ${{ needs.build-app.outputs.build-version }}

  deploy-dev:
    name: Deploy dev
    permissions:
      id-token: write
    if: |
      github.ref_name == 'master'
        && always()
        && needs.verdikjede-tester.outputs.pleiepenger == 'success'
        && needs.verdikjede-tester.outputs.livetssluttfase == 'success'
    needs: [ build-app, verdikjede-tester ]
    uses: navikt/ft-inntektsmelding/.github/workflows/deploy.yml@master
    with:
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
      namespace: k9saksbehandling
    secrets: inherit

  deploy-prod:
    name: Deploy prod
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: [ build-app, verdikjede-tester, deploy-dev ]
    uses: navikt/ft-inntektsmelding/.github/workflows/deploy.yml@master
    with:
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: prod-gcp
      namespace: k9saksbehandling
    secrets: inherit
