name: Bygg og deploy

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - '.editorconfig'
      - '.java-version'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'lokalutvikling/**'
      - '.github/*.yml'

jobs:
  build-app:
    name: Build
    permissions:
      contents: read
      packages: write
      id-token: write
      pull-requests: read
    uses: navikt/fp-gha-workflows/.github/workflows/build-app-no-db.yml@main
    with:
      build-image: ${{ github.ref_name == 'master' }} # default: true
      push-image: ${{ github.ref_name == 'master' }} # default: false
      namespace: teamforeldrepenger
    secrets: inherit

  verdikjede:
    name: Verdikjedetester
    permissions:
      contents: read
      id-token: write
    if: github.ref_name == 'master'
    needs: build-app
    uses: navikt/fp-autotest/.github/workflows/autotest.yml@master
    with:
      build-version: ${{ needs.build-app.outputs.build-version }}
      test-suite: verdikjede
    secrets: inherit

  notify:
    name: Notify
    if: github.ref_name == 'master' && (success() || failure()) && !contains(needs.*.result, 'skipped')
    needs: [ build-app, verdikjede ]
    uses: navikt/fp-autotest/.github/workflows/report-and-notify.yml@master
    with:
      verdikjede: ${{ needs.verdikjede.outputs.resultat }}
      build-version: ${{ needs.build-app.outputs.build-version }}
    secrets: inherit

  publish-image-k9:
    name: Build på nytt for publisering til k9saksbehandling i GAR
    if: github.ref_name == 'master'
    permissions:
      contents: read
      packages: write
      id-token: write
      pull-requests: read
    uses: navikt/fp-gha-workflows/.github/workflows/build-app-no-db.yml@main
    with:
      build-image: ${{ github.ref_name == 'master' }} # default: true
      push-image: ${{ github.ref_name == 'master' }} # default: false
      namespace: k9saksbehandling
      sonar-scan: false
    secrets: inherit

  deploy-dev-teamforeldrepenger:
    name: Deploy dev
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: [build-app, verdikjede]
    uses: navikt/ft-inntektsmelding/.github/workflows/deploy.yml@master
    with:
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
      namespace: teamforeldrepenger
    secrets: inherit

  deploy-prod-teamforeldrepenger:
    name: Deploy prod
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: [build-app, verdikjede, deploy-dev-teamforeldrepenger]
    uses: navikt/ft-inntektsmelding/.github/workflows/deploy.yml@master
    with:
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: prod-gcp
      namespace: teamforeldrepenger
    secrets: inherit

  deploy-dev-k9saksbehandling:
    name: Deploy dev
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: [publish-image-k9]
    uses: navikt/ft-inntektsmelding/.github/workflows/deploy.yml@master
    with:
      image: ${{ needs.publish-image-k9.outputs.build-version }}
      cluster: dev-gcp
      namespace: k9saksbehandling
    secrets: inherit

#  deploy-prod:
#    name: Deploy prod
#    permissions:
#      id-token: write
#    if: github.ref_name == 'master'
#    needs: [build-app]
#    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
#    with:
#      gar: true
#      image: ${{ needs.build-app.outputs.build-version }}
#      cluster: prod-gcp
#    secrets: inherit



