name: Bygg og deploy

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - '.editorconfig'
      - '.java-version'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'lokalutvikling/**'
      - '.github/*.yml'

jobs:
  build-app:
    name: Build
    permissions:
      contents: read
      packages: write
      id-token: write
      pull-requests: read
    uses: navikt/fp-gha-workflows/.github/workflows/build-app-postgres.yml@main
    with:
      postgres-user: ftinntektsmelding_unit
      build-image: ${{ github.ref_name == 'master' }} # default: true
      push-image: ${{ github.ref_name == 'master' }} # default: false
    secrets: inherit

  deploy-dev-teamforeldrepenger:
    name: Deploy dev
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: [build-app]
    uses: navikt/ft-inntektsmelding/.github/workflows/deploy.yml@master
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
      namespace: teamforeldrepenger
    secrets: inherit

  deploy-dev-k9saksbehandling:
    name: Deploy dev
    permissions:
      id-token: write
    if: github.ref_name == 'master'
    needs: [build-app]
    uses: navikt/ft-inntektsmelding/.github/workflows/deploy.yml@master
    with:
      gar: true
      image: ${{ needs.build-app.outputs.build-version }}
      cluster: dev-gcp
      namespace: k9saksbehandling
    secrets: inherit

#  deploy-prod:
#    name: Deploy prod
#    permissions:
#      id-token: write
#    if: github.ref_name == 'master'
#    needs: [build-app]
#    uses: navikt/fp-gha-workflows/.github/workflows/deploy.yml@main
#    with:
#      gar: true
#      image: ${{ needs.build-app.outputs.build-version }}
#      cluster: prod-gcp
#    secrets: inherit



