name: Deploy manuelt
on:
  workflow_dispatch:
    inputs:
      image:
        required: true
        type: string
        description: 'Image tag to deploy (example 2023.03.10.080433-f821119)'
      environment:
        required: true
        type: choice
        description: 'The environment to deployed to (dev|prod)'
        options:
          - dev
          - prod
      namespace:
        required: true
        type: choice
        description: 'teamforeldrepenger eller k9'
        options:
          - k9saksbehandling
          - teamforeldrepenger

jobs:
  deploy:
    name: Deploy dev
    permissions:
      id-token: write
    uses: navikt/ft-inntektsmelding/.github/workflows/deploy.yml@master
    with:
      image: ${{ inputs.image }}
      cluster: ${{ inputs.environment }}-gcp
      namespace: ${{ inputs.namespace }}
    secrets: inherit
